language: node_js

node_js:
  - "0.11"
  - "0.10"

env:
  - PORT=8080

install:
  - "npm install"
  - "npm install jasmine-node --global"
  - "npm install forever --global"

before_script:
  - "npm start"

after_script:
  - "npm stop"
